ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [
            "com.gatekeeper.plugins.SerializationKt.configureSerialization",
            "com.gatekeeper.plugins.MonitoringKt.configureMonitoring",
            "com.gatekeeper.plugins.DatabaseKt.configureDatabase",
            "com.gatekeeper.plugins.RedisKt.configureRedis",
            "com.gatekeeper.plugins.SecurityKt.configureSecurity",
            "com.gatekeeper.plugins.RoutingKt.configureRouting",
            "com.gatekeeper.gate.GateRoutesKt.configureGateRoutes"
        ]
    }
}